version: "3.7"

services:
    persafe:
        volumes:
            - persafe-data:/usr/persafe/uploads
            - persafe-database:/usr/persafe/database

volumes:
    nginx-data:
        name: "nginx-data"
    persafe-data:
        name: "persafe-data"
    persafe-database:
        name: "persafe-database"
